### PR TITLE
Enhance support for desktop platform

### PR DESCRIPTION
**Pull request by beroset**
This makes the selection of systemd service file a programmatically determined value, based on a SERVICE_NAME variable defined at the top level.  This should better allow both starfish and the desktop target to be correctly build from the same source.  Because the current version of Ubuntu Touch uses upstart rather than systemd, the variable is set to an empty value.  Because the Ubuntu Touch platform maintainers are reported to be migrating to systemd, support for that should only require changing this variable, selecting the sailfish version for the plugin (which alredy uses D-Bus and systemd), and supplying a new service file if needed.

### CODE REVIEW

**Comment by FlorentRevest** [comment]
Looks great overall! :) I would only ask you to rename `SERVICE_NAME` to `SYSTEMD_SERVICE_NAME` because in the context of a project configuration it's not immediately obvious what "service" means (it could mean a bit of everything) so I think it's worth properly qualifying it. Also I don't know how upstart calls these but if they are upstart services too, that would get confusing.

**Comment by beroset** [comment]
Done!

**Comment by FlorentRevest** [comment]
Okay this looks good to me but this got all entangled with https://github.com/AsteroidOS/asteroidsyncservice/pull/48 now :| 

Well, I told you I would notice if a PR is based on another but it looks like it was easy to overlook...

**Review by FlorentRevest — APPROVED** [review]

**Comment by beroset** [comment]
Everything should now be resolved.

**Pull request merged**
