### PR TITLE
Fix plugin cmake

### PR DESCRIPTION
**Pull request by beroset**
This fixes the asteroidsyncservice plugin build by adding the Qt5::Gui module and turning on AUTOMOC in the CMakeLists.txt file.

### CODE REVIEW

**Comment by beroset** [comment]
This depends on and incorporates the BlueZ refactoring patch.  I don't know how to separate the two.

**Comment by FlorentRevest** [comment]
[Only reviewing the "Fix the CMakeLists.txt file for plugin" commit here]

I'm surprised the Gui module is necessary here. What error do you get without the Gui module ? Because this is a simple QML module that wraps a DBus API I expect this should only depend on QtQuick but not QtGui.

**Comment by beroset** [comment]
You are right.  All that was need was AUTOMOC, so this rebased change can now be cleanly applied atop the current master.

**Comment by FlorentRevest** [comment]
Now you poked my curiosity :) why are the QtBluetooth and QtQuick dependencies here ? It looks like they would not be needed in asteroidsyncservice/ (the QML plug-in, I know, that folder name is stupid) since this is just a QML plugin that wraps DBus calls

**Comment by FlorentRevest** [comment]
Merging this because this is already a strict improvement and shouldn't be blocked on the previous comment. ut my question above stands ;)

**Pull request merged**
