### PR TITLE
Update dependancies and use harbour prefix

### PR DESCRIPTION
**Pull request by GeoffTearle**
Updates the libwatchfish dependency to use Piggz updated/fixed fork.
Additionally tweaks the background service to use the "harbour-" prefix.

### CODE REVIEW

**Comment by GeoffTearle** [comment]
@FlorentRevest This is  the first of two PR's to get starfish into a minimal working state.
I'll create the second PR after this one gets approved as it will be dependent on this.

**Comment by jrtberlin** [comment]
Thank you @GeoffTearle for taking the time to finally get [starfish](https://github.com/AsteroidOS/starfish) working. :tada: 

### Commit Message
Commit messages are secondary documentation and people read them to understand changes and processes when the primary documentation is not complete or outdated. Both @FlorentRevest and I did not know why the added `harbour-` prefix is necessary. After a bit of searching, I found out that [it ts a requirement ](https://harbour.jolla.com/faq#1.1.0) for [Jollas Harbour](https://harbour.jolla.com/). 

It would be great if you could include the reasoning behind the change in the commit message so that people in the future know why the change was made. The [commit message body](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) is the ideal place for that.

### Your Changes

Can you please remove the unnecessary empty lines in [asteroidsyncserviced.pro](https://github.com/AsteroidOS/asteroidsyncservice/blob/0a93523e3c4294b49a9b69582f6c69e178a4d76e/asteroidsyncserviced/asteroidsyncserviced.pro#L46-L47)?
The other changes look reasonable to me.

Thanks again for working on starfish!

---
Related issue: https://github.com/AsteroidOS/starfish/issues/4

**Comment by GeoffTearle** [comment]
My apologies for the commit message I'll get that tidied up today, and make the other requested changes.

On a side note, would you prefer that any PRs that I make in the future are a singe squashed commit, or have the preserved commit history?

**Comment by jrtberlin** [comment]
@GeoffTearle I prefer a clean commit history:
A commit history to document the process and make commits reusable in forks,... but without fixup commits,...
If there is a case where a squashed history makes sense there is always the ability to pick "squash and merge" on a PR.

**Review by jrtberlin — APPROVED** [review]
Thanks for improving on your PR.

**Comment by FlorentRevest** [comment]
Excellent work @GeoffTearle ! Looking forward to the next PRs, this is great :)

**Comment by GeoffTearle** [comment]
Thank you @jrtberlin and @FlorentRevest for taking the time to look at this!

**Pull request merged**
