### PR TITLE
Update SailfishOS dependencies to use CMake

### PR DESCRIPTION
**Pull request by GeoffTearle**
This PR makes changes to better support SailfishOS while using the CMake build system.

Included in the changes is updating the `libwatchfish` submodule to a CMake compatible fork, and minor changes to `libasteroid` so that it builds correctly under the older version of QT used on Sailfish.

### CODE REVIEW

**Comment by FlorentRevest** [comment]
The change looks good to me overall but could you clean up the git history ? :)

**Comment by haelge** [comment]
Is there still anything that prevents this pull request to be ready for review, or even ready to merge?

**Comment by GeoffTearle** [comment]
Hey! Unfortunately theres still a couple of things I need to clean up with this, one of the main ones being that the libasteroid submodule is currently pointing to my quite out of date fork.

Additionally I need to go back through libasteroid and add in some tweaks to properly handle comptibility with SailfishOS's old QT version, like beroset did with this repo.

**Comment by GeoffTearle** [comment]
Closing this for now, as its massively out of date.
Will attempt to re-open in the future when I have a bit more time to work on it

**Pull request closed without merging**
